IF OBJECT_ID('LOOPP.SP_GetAllRolesHab') IS NOT NULL
    DROP PROCEDURE LOOPP.SP_GetAllRolesHab
GO

CREATE PROCEDURE [LOOPP].[SP_GetAllRolesHab]
AS
BEGIN
	SELECT * FROM LOOPP.Roles
	WHERE baja_logica='False'
	ORDER BY nombre
END
GO